// types/supabase.ts
// Auto-generated by: npx supabase gen types typescript --project-id YOUR_PROJECT_ID
// Run this command after your Supabase project is set up to regenerate.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          supabase_id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          role: "PARENT" | "CAREGIVER" | "ADMIN";
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["profiles"]["Row"], "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      user_role: "PARENT" | "CAREGIVER" | "ADMIN";
      family_role: "OWNER" | "MEMBER" | "VIEWER";
      activity_type:
        | "LEARNING"
        | "PLAY"
        | "EXERCISE"
        | "READING"
        | "SOCIAL"
        | "CREATIVE"
        | "NUTRITION"
        | "SLEEP"
        | "HEALTH"
        | "OTHER";
      milestone_category:
        | "MOTOR"
        | "LANGUAGE"
        | "COGNITIVE"
        | "SOCIAL_EMOTIONAL"
        | "SELF_CARE"
        | "ACADEMIC";
      goal_status: "ACTIVE" | "COMPLETED" | "PAUSED" | "CANCELLED";
    };
  };
};
